language: cpp
compiler: gcc

env:
  - QT_BASE=48
  - QT_BASE=52

before_install:
  - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$QT_BASE" = "48" ]; then sudo add-apt-repository ppa:beineri/opt-qt487 -y; fi
  - if [ "$QT_BASE" = "52" ]; then sudo add-apt-repository ppa:beineri/opt-qt521 -y; fi

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq zlib1g-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++ gcc; export CXX="g++" CC="gcc"; $CXX --version; fi
  - if [ "$QT_BASE" = "48" ]; then sudo apt-get install -qq opt-qt4-qmake opt-qt4-dev-tools; source /opt/qt-4.8/bin/qt-4.8-env.sh; fi
  - if [ "$QT_BASE" = "52" ]; then sudo apt-get install -qq qt52base qt52declarative qt52quick1 qt52quickcontrols qt52location qt52tools; source /opt/qt52/bin/qt52-env.sh; fi

script:
  - qmake fahrplan2.pro
  - make
  
branches:
  only:
    - master
